#!/bin/sh /etc/rc.common

START=79
STOP=19
USE_PROCD=1

PROG=/usr/libexec/lan-analyzer/lan-analyzer.sh

start_service() {
	config_load lan-analyzer
	local enabled
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger lan-analyzer network dhcp firewall
}

reload_service() {
	stop
	start
}

